k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /tmp/k9s-screens
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    crumbsless: false
    reactive: false
    noIcons: false
    skin: monokai
  logger:
    tail: 200
    buffer: 5000
    sinceSeconds: 300
    textWrap: false
    showTime: false
  currentContext: default
  currentCluster: default
